### ISSUE TITLE
Honestly, is this project dead?

### ISSUE THREAD

**Issue by sunshineo** [jaredhanson/passport-local#102]
It seems like nothing happened in more than a year. (8 month for https://github.com/jaredhanson/passport )
I just tried to follow the example at http://passportjs.org/guide/username-password/ for a simple username password login and it completely does not work. Always get 400 bad request.
I suspect the expressjs moved forward on something and this project just can't keep up.

**Comment by cfogelberg** [comment]
Hey just a quick comment from another user of passport-local, which is that I have it working in my app (express 4.11.x passport 0.2.x, passport-local 1.0.x). Sometimes when I make a typo in my passport code though it fails silently and I'm just about to post an issue for that. So that we can help you can you please post a jsfiddle or gist with your code?

**Comment by cfogelberg** [comment]
Follow up: I'm holding off on my issue, actually it seems to not be failing silently at all - I need to drill a little further :)

**Comment by sunshineo** [comment]
I went with another alternative. I'm simply managing session using express. I don't have a jsfiddle to show. I opened this issue to see if this project get any attention from the author/team at all. I feel I'm right about that it is dead. I hope this issue can show as a warning for new comers to move away from using this.

Of course, if I'm completely wrong, someone will see this and close the issue.

**Comment by GochoMugo** [comment]
I thought that this project was too inactive until I read all the source code. There's is **not** much to be done. Except **good documentation**.

What do you think?

**Comment by sunshineo** [comment]
@GochoMugo Maybe you are right, but with my hundreds times of documentation reading experience and still cannot figure this one out, there could be something wrong.

**Comment by GochoMugo** [comment]
How do you think we should handle this? Its OSS. We could fork and work on it in another repo altogether.

**Comment by sunshineo** [comment]
@GochoMugo As I said above, I found an alternative directly in express.js . I don't think I have the drive to bring this project to a better state.

**Comment by fmalk** [comment]
I consider this project stable, far from dead. I've been using passportjs for years and this Strategy does well what's supposed to do. It's just not that many lines of code, and will probably stay that way unless a major passportjs update comes along.

**Comment by sunshineo** [comment]
@fmalk Fair enough. I may made some silly mistake to not have this working properly with Express.js .

**Comment by jaredhanson** [comment]
Nope.

**Comment by mtimofiiv** [comment]
The `Bad Request` error is something that happens when the username or password is not found at the time of this middleware's execution. So, for example, if you are using JSON, make sure your JSON body parser is added to the middleware stack before this middleware. Also double check that you have set the correct field names in the options you pass the strategy.
